const app=document.getElementById('app'),API=YT_API;let S=JSON.parse(localStorage.getItem('yt_open_staff')||'{}');let poll=null,qrTimer=null,current=null;
function save(){localStorage.setItem('yt_open_staff',JSON.stringify(S))}function esc(s){return String(s??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]))}function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2300)}
function shell(body){app.innerHTML=`<div class="topbar"><div class="brand">YETIPSY · STAFF</div><div class="top-actions">${S.staff?`<span class="badge">${esc(S.staff.name)}</span>`:''}<button class="iconBtn" id="logout">LOGOUT</button></div></div>${body}`;document.getElementById('logout').onclick=()=>{localStorage.removeItem('yt_open_staff');location.reload()}}
function err(e){return({active_session_exists:'已经有一场活动正在进行',staff_auth_required:'Staff 登入已过期',invalid_session_state:'当前阶段不能这样操作',table_full:'目标桌已满',game_not_live:'活动还没正式 START GAME'})[e]||e||'操作失败'}
async function init(){if(!S.authToken)return login();const r=await API.post('staffDashboard',{authToken:S.authToken});if(!r.ok)return login();S.staff=r.staff;save();dashboard(r)}
function login(){clearInterval(poll);shell(`<div class="hero"><div class="kicker">TONIGHT CONTROL</div><h1 class="display">今晚<br>开局。</h1><p class="lead">Staff / Host 后台</p></div><div class="card"><label>Staff ID</label><input class="field" id="sid" value="staff"><label>PIN</label><input class="field" id="pin" inputmode="numeric" type="password"></div><button class="btn primary" id="login">LOGIN</button>`);document.getElementById('login').onclick=async()=>{const r=await API.post('staffLogin',{staffId:document.getElementById('sid').value,pin:document.getElementById('pin').value});if(!r.ok)return toast('登入失败');S.authToken=r.auth_token;S.staff=r.staff;save();init()}}
function dashboard(r){current=r;clearInterval(poll);clearInterval(qrTimer);if(!r.session)return noSession();const s=r.session;const controls=s.status==='CHECK_IN'?`<button class="btn primary" id="lock">LOCK TABLES</button>`:s.status==='TABLES_LOCKED'?`<button class="btn primary" id="start">START GAME</button>`:s.status==='LIVE'?`<button class="btn danger" id="end">END SESSION</button>`:'';
shell(`<div class="row"><div class="grow"><div class="kicker">YT GAME #${String(s.game_no).padStart(3,'0')}</div><h1 class="title" style="margin-bottom:4px">${esc(s.status)}</h1><div class="small">${r.checkin_count} / ${s.capacity} checked in · ${s.table_count} tables</div></div><span class="status ${s.status==='LIVE'?'live':''}">${esc(s.session_id)}</span></div>
${s.status==='CHECK_IN'?qrSection():''}
<div class="toolbar" style="margin:14px 0">${controls}<button class="btn secondary" id="refresh">REFRESH</button></div>
<div class="sectionTitle"><h2>Tables</h2><span>Mission content hidden from Staff</span></div><div class="grid2">${r.tables.map(tableCard).join('')}</div>
${s.status==='LIVE'?hostTools(r):''}
<div class="sectionTitle"><h2>Reward Redemption</h2></div><div class="card"><div class="row"><input class="field grow" id="redeemToken" inputmode="numeric" maxlength="6" placeholder="6-digit redemption code"><button class="btn primary" id="redeem" style="width:auto;margin:0">CONFIRM</button></div></div>`);
wireDashboard(r);if(s.status==='CHECK_IN')refreshQr();poll=setInterval(refresh,5000)}
function noSession(){shell(`<div class="hero"><div class="kicker">NO ACTIVE SESSION</div><h1 class="title">开一场新的「今晚开局」。</h1></div><div class="card"><div class="grid3"><div><label>Capacity</label><input class="field" id="capacity" type="number" value="10"></div><div><label>Tables</label><input class="field" id="tables" type="number" value="2"></div><div><label>Seats / Table</label><input class="field" id="size" type="number" value="5"></div></div><label>Start Time（显示用）</label><input class="field" id="time" type="time"><div class="small" style="margin-top:10px">默认开启 Hidden Mission / Coin / Team Score / Auto Assign。</div></div><button class="btn primary" id="open">OPEN SESSION</button>`);document.getElementById('open').onclick=async()=>{const b=document.getElementById('open');b.disabled=true;const r=await API.post('createSession',{authToken:S.authToken,capacity:+document.getElementById('capacity').value,tableCount:+document.getElementById('tables').value,tableSize:+document.getElementById('size').value,startTime:document.getElementById('time').value,hiddenMissionEnabled:true,coinEnabled:true,leaderboardEnabled:true,autoAssign:true});if(!r.ok){b.disabled=false;return toast(err(r.error))}refresh()}}
function qrSection(){return `<div class="card gold"><div class="kicker">TONIGHT CHECK-IN QR</div><div class="qrWrap" id="qr"></div><div class="countdownText" id="qrCount">Generating rotating token…</div><pre class="codebox" id="joinLink"></pre></div>`}
function tableCard(t){return `<div class="card tableCard"><div class="row"><div class="grow"><h3>TABLE ${esc(t.table_id)}</h3><span class="small">${t.players.length}/${t.capacity}</span></div><div class="coin" style="font-size:26px">${t.score}</div></div>${t.players.length?t.players.map(p=>`<div class="playerLine"><div><b>${esc(p.nickname)}</b><br><span>${esc(p.player_id)} · ${esc(p.seat_code)} · Mission ${esc(p.mission_status)}</span></div><select class="moveSelect" data-player="${esc(p.player_id)}" style="width:auto"><option value="">MOVE…</option>${current.tables.filter(x=>x.table_id!==t.table_id).map(x=>`<option value="${esc(x.table_id)}">TABLE ${esc(x.table_id)}</option>`).join('')}</select></div>`).join(''):'<div class="small">No players yet</div>'}</div>`}
function hostTools(r){const players=r.tables.flatMap(t=>t.players.map(p=>({...p,table_id:t.table_id})));return `<div class="sectionTitle"><h2>Host Event</h2><span>Only Host events change Team Score</span></div><div class="card"><div class="grid2"><div><label>Stage Player</label><select id="stagePlayer">${players.map(p=>`<option value="${esc(p.player_id)}">${esc(p.nickname)} · ${esc(p.player_id)}</option>`).join('')}</select><button class="btn secondary" id="stageBtn">RECORD STAGE</button></div><div><label>Formal Table Match</label><select id="playerA">${players.map(p=>`<option value="${esc(p.player_id)}">${esc(p.nickname)} · T${esc(p.table_id)}</option>`).join('')}</select><select id="playerB" style="margin-top:8px">${players.map(p=>`<option value="${esc(p.player_id)}">${esc(p.nickname)} · T${esc(p.table_id)}</option>`).join('')}</select><input class="field" id="matchGame" style="margin-top:8px" placeholder="反应杯 / 自选"><button class="btn primary" id="newMatch">NEW TABLE MATCH</button></div></div></div>${r.active_matches.length?`<div class="sectionTitle"><h2>Active Match</h2></div>${r.active_matches.map(m=>`<div class="card"><b>${esc(m.game)}</b><div class="small">TABLE ${esc(m.table_a)} VS TABLE ${esc(m.table_b)}</div><div class="grid2"><button class="btn secondary winBtn" data-id="${esc(m.match_id)}" data-table="${esc(m.table_a)}">${esc(m.table_a)} WIN</button><button class="btn secondary winBtn" data-id="${esc(m.match_id)}" data-table="${esc(m.table_b)}">${esc(m.table_b)} WIN</button></div></div>`).join('')}`:''}`}
function wireDashboard(r){document.getElementById('refresh').onclick=refresh;document.getElementById('lock')&&(document.getElementById('lock').onclick=()=>act('lockTables'));document.getElementById('start')&&(document.getElementById('start').onclick=()=>act('startGame'));document.getElementById('end')&&(document.getElementById('end').onclick=()=>{if(confirm('结束本场？结束后不能继续签到和 Challenge。'))act('endSession')});document.querySelectorAll('.moveSelect').forEach(s=>s.onchange=async()=>{if(!s.value)return;const r=await API.post('movePlayer',{authToken:S.authToken,sessionId:current.session.session_id,playerId:s.dataset.player,tableId:s.value});if(!r.ok)return toast(err(r.error));toast('已换桌');refresh()});const st=document.getElementById('stageBtn');if(st)st.onclick=async()=>{const r=await API.post('recordStagePlayer',{authToken:S.authToken,sessionId:current.session.session_id,playerId:document.getElementById('stagePlayer').value});toast(r.ok?'已记录 STAGE':'失败')};const nm=document.getElementById('newMatch');if(nm)nm.onclick=async()=>{const a=playerObj(document.getElementById('playerA').value),b=playerObj(document.getElementById('playerB').value);if(!a||!b||a.table_id===b.table_id)return toast('请选择不同桌代表');const x=await API.post('createTableMatch',{authToken:S.authToken,sessionId:current.session.session_id,tableA:a.table_id,tableB:b.table_id,playerA:a.player_id,playerB:b.player_id,game:document.getElementById('matchGame').value||'自选'});if(!x.ok)return toast(err(x.error));toast('Formal Match 已建立');refresh()};document.querySelectorAll('.winBtn').forEach(b=>b.onclick=async()=>{const x=await API.post('finishTableMatch',{authToken:S.authToken,matchId:b.dataset.id,winnerTable:b.dataset.table});if(!x.ok)return toast(err(x.error));toast('比分已更新');refresh()});document.getElementById('redeem').onclick=async()=>{const token=document.getElementById('redeemToken').value;const x=await API.post('confirmRedemption',{authToken:S.authToken,token});if(!x.ok)return toast(err(x.error));toast(`兑换成功 · 扣 ${x.cost} Coin`);document.getElementById('redeemToken').value=''}}
function playerObj(id){for(const t of current.tables){const p=t.players.find(x=>x.player_id===id);if(p)return{...p,table_id:t.table_id}}return null}
async function act(action){const r=await API.post(action,{authToken:S.authToken,sessionId:current.session.session_id});if(!r.ok)return toast(err(r.error));refresh()}
async function refresh(){const r=await API.post('staffDashboard',{authToken:S.authToken,sessionId:current?.session?.session_id});if(!r.ok){if(r.error==='staff_auth_required')return login();return}dashboard(r)}
async function refreshQr(){clearInterval(qrTimer);async function draw(){const r=await API.post('getCheckinToken',{authToken:S.authToken,sessionId:current.session.session_id});if(!r.ok)return;const u=new URL('index.html',location.href);u.searchParams.set('sid',r.session_id);u.searchParams.set('token',r.token);const q=document.getElementById('qr');if(!q)return;q.innerHTML='';if(window.QRCode)new QRCode(q,{text:u.toString(),width:230,height:230,correctLevel:QRCode.CorrectLevel.M});else q.textContent='QR library unavailable';document.getElementById('joinLink').textContent=u.toString();document.getElementById('qrCount').textContent=`Token rotates automatically · ~${Math.ceil(r.expires_in_ms/1000)}s`;}await draw();qrTimer=setInterval(draw,20000)}
init();
